I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 82, in script
    show ben talking_mouth_open fade at midleft
Exception: Image 'ben talking_mouth_open' does not accept attributes 'fade'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 82, in script
    show ben talking_mouth_open fade at midleft
  File "C:\Users\Rhea2\Desktop\renpy\renpy-8.2.1-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Rhea2\Desktop\renpy\renpy-8.2.1-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Rhea2\Desktop\renpy\renpy-8.2.1-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Rhea2\Desktop\renpy\renpy-8.2.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Rhea2\Desktop\renpy\renpy-8.2.1-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\Rhea2\Desktop\renpy\renpy-8.2.1-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'ben talking_mouth_open' does not accept attributes 'fade'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Enigma 1.0
Wed Apr 24 14:18:58 2024
